import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import "./globals.css";
import theme from "@/theme";

import { Roboto } from "next/font/google";
import Header from "@/Components/Header/Header";
import Sidebar from "@/Components/Sidebar/Sidebar";
import Loading from "./Loading/Loading";
import { Suspense } from "react";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-arp="">
      <head></head>
      <body className={roboto.variable} inmaintabuse="1">
        <AppRouterCacheProvider options={{ key: "css", enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <Sidebar>
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </Sidebar>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
